### PR TITLE
Switch to ruff linting

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by hyanwong** [comment]
Now that we have merged the phase_singleton branch, shall I "ruffen" everything up, and get this merged in? Will it mess up any of your current unmerged work, @nspope ?

**Comment by nspope** [comment]
I'm working on the missing data mask ATM ... but it seems like the per-file changes here are pretty minimal so maybe it's not a big deal. Is ruff replacing flake8 in the precommit hooks?

**Comment by nspope** [comment]
I'd say go for it-- I can focus on other stuff in the meanwhile

**Comment by hyanwong** [comment]
> I'm working on the missing data mask ATM ... but it seems like the per-file changes here are pretty minimal so maybe it's not a big deal. Is ruff replacing flake8 in the precommit hooks?

Yes, I think it replaces everything, and is faster.

**Pull request closed without merging**
