### PR TITLE
Address underflow in log-sum-exp

### PR DESCRIPTION
**Pull request by awohns**
The current implementation "log-sum-exp" in the `LogLikelihoods` class caused underflow in extreme cases on a few human chromosomes. This is because we simply bring the log values into linear space to sum them: the naive implementation of log-sum-exp.
This PR simply changes to using the "streaming'" version of log-sum-exp that was also implemented but unused

### CODE REVIEW

**Comment by hyanwong** [comment]
ISTR that we didn't use it because it was a bit slower, but stability should trump speed, so just merge this I think.

**Comment by hyanwong** [comment]
Oh, actually, perhaps add a quick unit test that checks it does the right thing with with `-np.inf` / `0` etc?

**Comment by awohns** [comment]
Hmm, I think the check should be, does it do the right thing with very small values that would underflow in linear space but are captured in log space. i.e.:
```
import numpy as np

X = [-800, -801]
r = 0
for x in X:
    r += np.exp(x) # underflow so that -746 term goes to 0 but -745 is captured

underflowed_answer = np.log(r) 

def logsumexp(X):
        alpha = -np.Inf
        r = 0.0
        for x in X:
            if x != -np.Inf:
                if x <= alpha:
                    r += np.exp(x - alpha)
                else:
                    r *= np.exp(alpha - x)
                    r += 1.0
                    alpha = x
        return np.log(r) + alpha

correct_answer = logsumexp(X)

```

**Comment by hyanwong** [comment]
Yes, that would be useful too.

**Comment by awohns** [comment]
Not sure I'm following what you mean

**Comment by hyanwong** [comment]
In the streaming code there's a line that says `if x != -np.Inf:`, so we should check that it works when `x==-np.Inf`

**Comment by awohns** [comment]
Thanks @hyanwong, I've written two tests to address these points

**Comment by hyanwong** [comment]
Great. Merge it!

**Pull request merged**
