### PR TITLE
Default to not filtering sites, pops, indivs in preprocess

### LINKED ISSUE #178: Change preprocess_ts() defaults
[`tsinfer` issue 491](https://github.com/tskit-dev/tsinfer/issues/491) identified a downstream issue caused when`preprocess_ts` removes sites.
Right now `preprocess_ts` [outputs a warning](https://github.com/tskit-dev/tsdate/blob/af8bcd58fde1b95ff1d7d9f7bdc3f111b51af37a/tsdate/util.py#L138) if the number of sites changes, which says:

>"Different number of sites after preprocessing. Try using **{'filter_sites:' False} to avoid this"

Do we actually want `filter_sites=False` as a default? Interested to hear your opinion @hyanwong

### PR DESCRIPTION
**Pull request by hyanwong**
Fixes #178

### CODE REVIEW

**Comment by hyanwong** [comment]
I think this is a no-brainer. Could you check I'm not missing something @awohns. I think preprocessing shouldn't remove any sites by default. Sites in regions that have been trimmed will not be associated with any edges, so simply won't be used by tsdate (which is correct).

**Comment by hyanwong** [comment]
I think I should just merge this, but it would be useful to get a quick look-over, either by @awohns or @benjeffery perhaps? I don't think it's very controversial: tsdate should only touch the node times, and not delete other stuff from the ts, even if that includes unreferenced sites, populations, etc.

**Review by benjeffery — APPROVED** [review]
Seems to make sense to me - although I note that it is no longer possible to get the default `simplify` behaviour with this change. That's fine as it stands as it is a boolean flag - but if simplify changed it would be a problem. Maybe the default here should be `False`, such that passing `None` still gets the default behaviour?

**Comment by hyanwong** [comment]
Oh yes, that's a good call. I know that we usually set `None` as the default, but I think your consideration overrides that. Thanks for the suggestion.

**Pull request merged**
