### PR TITLE
Start addressing #65

### PR DESCRIPTION
**Pull request by hyanwong**
We still need to deal with NaNs in the forwards matrix when calling `backward_algorithm()`. These should mark dangling nodes, although I'm slightly worried that other bugs might cause NaNs too, so perhaps that isn't such a good convention to establish. Other suggestions welcome (perhaps np.inf?)

### CODE REVIEW

**Comment by hyanwong** [comment]
Just revisiting this. We now have a specific tskit Nan: `tskit.UNKNOWN_TIME`, so we should be using this for dangling nodes, if we are still thinking of doing this (I'm not sure if it's relevant any more)

**Comment by awohns** [comment]
Right now we error out if we see dangling nodes. #38 and #65 are marked on the "wish list". Definitely seems like something that we _should_ do. Perhaps in release 1.1

**Comment by hyanwong** [comment]
> Right now we error out if we see dangling nodes. #38 and #65 are marked on the "wish list". Definitely seems like something that we _should_ do. Perhaps in release 1.1

Yes, perfect. It actually helps us a lot that there is a *specific* NaN we can use to mean "unknown", which we won't confuse with NaNs produced for other reasons.

**Comment by hyanwong** [comment]
Closing this due to inactivity: we'll end up implementing something better for historical samples using variational_gamma anyway.

**Pull request closed without merging**
