### PR TITLE
fix SVG logo

### PR DESCRIPTION
**Pull request by awohns**

### CODE REVIEW

**Comment by hyanwong** [comment]
Hmm, looks off to me, @awohns, sorry!: 
image

Have you tried the font I sent you?

**Comment by awohns** [comment]
Strange, this is what it looks like for me. I used Aglet Slab, same font as tskit

**Comment by awohns** [comment]
Strange, this is what it looks like for me. I used Aglet Slab, same font as tskit

Screenshot 2020-11-23 at 1 53 32 PM

**Comment by hyanwong** [comment]
Did you embed the font, in the svg, though? If not, and the font isn't on the user's system, then the SVG library will do a font substitution, which is why I see the bad logo.

Shouldn't make a difference for the pdf, though.

If you are doing it in (say) Inkscape, you can probably convert the characters to a path instead, which would save doing the substitution.

**Comment by hyanwong** [comment]
P.s. isn't the circle of the "d" a bit small? Try putting the actual letter d from that font in there, then overlaying the clock as near to it as possible before deleting the d

**Pull request merged**
