### PR TITLE
Upgrade circle CI image

### PR DESCRIPTION
**Pull request by benjeffery**

### CODE REVIEW

**Comment by hyanwong** [comment]
The failing test is fixed by #192

**Comment by hyanwong** [comment]
Can probably commit this now, and then I'll update #192 to get the tests working again? Or I could add this commit to #192?

**Comment by benjeffery** [comment]
Ah only just seen your comment. #192 fixes this in a better way so still commit that!

**Review by hyanwong — APPROVED** [review]

**Comment by hyanwong** [comment]
LGTM. Commit this now I reckon.

**Pull request merged**
